# Generated by Django 3.2.6 on 2021-08-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0002_auto_20210814_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopost_8',
            name='title',
            field=models.CharField(default='忘记输入标题', max_length=200),
        ),
        migrations.AddField(
            model_name='infopost_9',
            name='title',
            field=models.CharField(default='忘记输入标题', max_length=200),
        ),
        migrations.AlterField(
            model_name='infopost_7',
            name='title',
            field=models.CharField(default='忘记输入标题', max_length=200),
        ),
    ]
