# Generated by Django 3.2.6 on 2021-08-16 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0003_auto_20210814_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopost_7',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 7, 17, 15, 532065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infopost_9',
            name='answer',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='infopost_9',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 7, 17, 15, 536083, tzinfo=utc)),
        ),
    ]
