# Generated by Django 3.2.6 on 2021-08-18 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0004_auto_20210816_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopost_7',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 7, 4, 44, 494947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infopost_9',
            name='answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infopost_9',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
