# Generated by Django 3.2.6 on 2021-08-18 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0005_auto_20210818_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopost_7',
            name='answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infopost_7',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='infopost_8',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
